### ISSUE TITLE
python required for npm install since 19.2.46 ?

### ISSUE THREAD

**Issue by Ikaer** [syncfusion/ej2-javascript-ui-controls#116]
Hi,
I would like to know if python have become a requirement since the 19.2.46 to install ej2 via npm ?

if I try to install the 19.2.44 on an empty folder (with just an npm init to initialise the package.json), I've got no warnings/errors
```
F:\Users\xlefebvre\syncfusion_npm_test>npm install @syncfusion/ej2@19.2.44
npm WARN syncfusion_npm_test@1.0.0 No description
npm WARN syncfusion_npm_test@1.0.0 No repository field.

+ @syncfusion/ej2@19.2.44
added 72 packages from 35 contributors and audited 72 packages in 8.814s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

but if I try the 19.2.46, I've fot a bunch of warnings and an error from gyp not founding python. Also the folder /node_mofules/@syncfusion/ej2 is not created, only the the /node_modules/@syncfusion/ej2-* folders (like ej2-grids)

```
F:\Users\xlefebvre\syncfusion_npm_test>npm install @syncfusion/ej2@19.2.46
npm WARN deprecated request@2.79.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> node-sass@4.7.2 install F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-72_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 postinstall F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\Users\xlefebvre\syncfusion_npm_test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (F:\Users\xlefebvre\syncfusion_npm_test\node_modules\graceful-fs\polyfills.js:299:20)
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Users\\xlefebvre\\syncfusion_npm_test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\Users\xlefebvre\syncfusion_npm_test\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back har-validator@2.0.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'F:\Users\xlefebvre\syncfusion_npm_test\node_modules\request\node_modules'
npm WARN syncfusion_npm_test@1.0.0 No description
npm WARN syncfusion_npm_test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xlefebvre\AppData\Roaming\npm-cache\_logs\2021-07-10T16_08_32_267Z-debug.log

```

Thanks in advance for you assistance.

**Comment by jesusarockias** [comment]
Sorry for the inconvenience.

We have already logged a bug report on this and we expect that it will be included with our this week patch release on July 14, 2021. You can track the progress using the below feedback.

https://www.syncfusion.com/feedback/26799/resolve-the-issue-in-latest-version-of-ej2-package

**Comment by Mydeen-SN** [comment]
We are glad that we have fixed the reported issue and we request you to update to the latest version of Syncfusion packages.
