### ISSUE TITLE
ej2.min.js:10 Uncaught TypeError: this.parent.dataSource.adaptor.getModuleName is not a function

### ISSUE THREAD

**Issue by Lukkian** [syncfusion/ej2-javascript-ui-controls#138]
I'm facing this error when trying to filter the data grid using ej2 19.4.42, version 19.4.41 doesn't have the problem.

```
ej2.min.js:10 Uncaught TypeError: this.parent.dataSource.adaptor.getModuleName is not a function
    at e.updateModel (ej2.min.js:10:8461647)
    at e.filterByColumn (ej2.min.js:10:8469062)
    at e.onTimerTick (ej2.min.js:10:8480226)
    at ej2.min.js:10:8479428
e.updateModel @ ej2.min.js:10
e.filterByColumn @ ej2.min.js:10
e.onTimerTick @ ej2.min.js:10
(anonymous) @ ej2.min.js:10
setInterval (async)
e.startTimer @ ej2.min.js:10
e.processFilter @ ej2.min.js:10
e.keyUpHandler @ ej2.min.js:10
e.notify @ ej2.min.js:10
t.notify @ ej2.min.js:10
t.keyActionHandler @ ej2.min.js:10
r.keyPressHandler @ ej2.min.js:10
```
CDN tested:

https://cdn.syncfusion.com/ej2/19.4.41/dist/ej2.min.js > OK
https://cdn.syncfusion.com/ej2/19.4.42/dist/ej2.min.js > FILTER ERROR

**Comment by Lukkian** [comment]
Version [19.4.47](https://github.com/syncfusion/ej2-javascript-ui-controls/releases/tag/v19.4.47) released today seems to fix the problem, thank you very much.
