### ISSUE TITLE
pdfviewer: js error when trying to add a form field

### ISSUE THREAD

**Issue by dianasotirova** [syncfusion/ej2-javascript-ui-controls#140]
With a certain pdf file when I try to add a new form field via the form designer I got a js error:

common.min.js:603523 Uncaught TypeError: Cannot read properties of undefined (reading 'addAction')
    at NodeDrawingTool.push../node_modules/@syncfusion/ej2-pdfviewer/src/pdfviewer/drawing/tools.js.NodeDrawingTool.mouseDown (common.min.js:603523:44)
    at PdfViewerBase.push../node_modules/@syncfusion/ej2-pdfviewer/src/pdfviewer/base/pdfviewer-base.js.PdfViewerBase.diagramMouseDown (common.min.js:590423:23)
    at HTMLDivElement.PdfViewerBase.viewerContainerOnMousedown (common.min.js:583385:23)

Can you advise that the problem migth be?

**Comment by dianasotirova** [comment]
I am creating the pdf viewer with the annotation module. The problem is observed only with one particular file. And the problem is also available on the online demo.

**Comment by DhivyaBharathi1307** [comment]
Hi Team,

We suspect that the reported issue might be document-specific. Could you please share the PDF document in which you are facing this issue? It will be helpful for us to investigate further and assist you better.

Regards,
Dhivya.

**Comment by syncsiva** [comment]
This issue has not had any activity for 2 weeks. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
