### ISSUE TITLE
npm run error

### ISSUE THREAD

**Issue by Cinemacloud** [syncfusion/ej2-javascript-ui-controls#170]
From example on syncfusion file manager quick start example

➜ npm run start

> ej2-quickstart@0.0.1 start
> gulp start

[09:49:45] Using gulpfile /usr/share/nginx/quickstart/gulpfile.js
[09:49:45] Starting 'start'...
[09:49:45] Starting 'compile'...
[09:49:45] Starting '<anonymous>'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject()) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
error TS5101: Option 'suppressImplicitAnyIndexErrors' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
TypeScript: 1 options error
TypeScript: emit failed
[09:49:52] '<anonymous>' errored after 6.49 s
[09:49:52] Error: TypeScript: Compilation failed
    at Output.mightFinish (/usr/share/nginx/quickstart/node_modules/gulp-typescript/release/output.js:131:43)
    at Output.finish (/usr/share/nginx/quickstart/node_modules/gulp-typescript/release/output.js:123:14)
    at ProjectCompiler.inputDone (/usr/share/nginx/quickstart/node_modules/gulp-typescript/release/compiler.js:97:29)
    at CompileStream.end (/usr/share/nginx/quickstart/node_modules/gulp-typescript/release/project.js:125:31)
    at DestroyableTransform.onend (/usr/share/nginx/quickstart/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)
    at DestroyableTransform.emit (node:events:525:35)
    at DestroyableTransform.emit (node:domain:552:15)
    at endReadableNT (/usr/share/nginx/quickstart/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[09:49:52] 'compile' errored after 6.49 s
[09:49:52] 'start' errored after 6.5 s

**Comment by Indhumathy-Loganathan** [comment]
Hi @Cinemacloud,

We were able to face the reported issue on our end. We suggest you use our upgraded [quickstart](https://github.com/SyncfusionExamples/ej2-quickstart-webpack) seed to create the File Manager component. Follow the below steps to add File Manager component in the sample.

1.	Clone the [quickstart](https://github.com/SyncfusionExamples/ej2-quickstart-webpack) sample and run **“npm install”** command. This application is integrated with the webpack.config.js configuration and uses the latest version of the **webpack-cli**. It requires **node v14.15.0** or higher.
2.	Import the necessary CSS styles in the **~/src/styles/styles.css** file - https://ej2.syncfusion.com/documentation/file-manager/getting-started#adding-style-sheet-to-the-application.
3.	Add the File Manager code to the **~/src/index.html** file and JavaScript code to the **~/src/app/app.ts** file - https://ej2.syncfusion.com/documentation/file-manager/getting-started#initialize-the-file-manager.
4.	Run the application using **“npm run start”** command.

We have already updated this sample on our common getting started page and will refresh all the component getting started pages in any of our upcoming releases.

https://ej2.syncfusion.com/documentation/getting-started/quick-start

**Comment by maheshtps** [comment]
We are working on all the components getting started pages. It will be resolved in the current 2023 volume 4 release.

**Comment by gsumankumar** [comment]
We have updated the "Getting Started" documents for all components and refreshed them live. Thank you for bringing the documentation issue to our attention.
